name: Build and Deploy
on:
  push:
    branches:
      - main  # Assurez-vous que cela correspond à votre branche de développement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'  # Utilisez la version de Node.js qui correspond à votre projet
      - run: npm install
      - run: npm run build
      - run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}