name: Build and Deploy
on:
  push:
    branches:
      - main  # Assurez-vous que cela correspond à votre branche de développement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adaptez à la version de Node.js de votre projet
      - name: Config Git
        run: |
          git config --global user.email "tech@data-players.com"
          git config --global user.name "Data Players"
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      - name: Deploy
        run: npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        working-directory: ./frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}